import { AiFillPrinter } from "react-icons/ai"
export const progress = [
    {
        id: 1,
        link: "",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 13,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "red"
    },
    {
        id: 2,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 76,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green"
    },
    {
        id: 3,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 99,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },
    {
        id: 4,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 68,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "purple",
    },
    {
        id: 5,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 70,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "purple",
    },
    {
        id: 6,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 94,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },
    {
        id: 7,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 78,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },
    {
        id: 8,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 47,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "orange",
    },
    {
        id: 9,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 67,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "purple",
    },
    {
        id: 10,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 53,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "purple",
    },
    {
        id: 11,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 44,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: 'orange',

    },
    {
        id: 12,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 100,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },
    {
        id: 13,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 50,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "orange"
    },
    {
        id: 14,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 15,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "red"
    },
    {
        id: 15,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: -8,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },

    {
        id: 16,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 100,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },


    {
        id: 17,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 100,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },


    {
        id: 18,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 76,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },


    {
        id: 19,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 94,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },


    {
        id: 20,
        link: "B1J3Y20",
        title: 'Modern Web App Development',
        students: 11,
        students_progress: 92,
        start_Date: "",
        freeCollected: "17,220",
        freeDue: "116,066",
        prints: AiFillPrinter,
        bgColor: "green",
    },

]